name: 'Test'

on:
  #push:
  schedule:
     - cron: '0 */2 */3 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
     # runs-on: macos-latest
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
          with:
            python-version: '3.9.5'
#         - name: 'Set up Python'
#           uses: actions/setup-python@v2
#           with:
#             python-version: '3.9.10'
        - name: 'Install requirements'
          run: |
            pip3 install -r ./requirements.txt
        - name: 'Working'
          env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            BARKKEY: ${{ secrets.BARKKEY }}
          run: |
            python3 ./main.py
        
